/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
  public char findTheDifference(String s, String t) {
        
    int[] map = new int[26];
    for(int i=0; i<t.length(); i++) {
        if(i<s.length())  map[s.charAt(i)-'a']++;
        map[t.charAt(i)-'a']--;
    }
    for(int i=0; i<26; i++) {
        if(map[i] < 0)  return (char)(i+'a');
    }
    return '0';
}
}